const buenosDias = new Audio('./audios/saludosBuenosdias.mp3');
const buenas1 = new Audio('./audios/saludosBuenas1.mp3');
const buenas2 = new Audio('./audios/saludosBuenas2.mp3');
const buenas3 = new Audio('./audios/saludosBuenas3.mp3');
const anibal = new Audio('./audios/anibal.mp3');
const paulo = new Audio('./audios/paulo-londra.mp3');
const pauloTrans = new Audio('./audios/paulo-trans.mp3');
const chumba = new Audio('./audios/saludosChumba.mp3');
const garmendia = new Audio('./audios/german-garmendia.mp3');
const zumbi1 = new Audio('./audios/saludosZumbi.mp3');
const zumbi2 = new Audio('./audios/saludosZumbi2.mp3');
const fiumba1 = new Audio('./audios/saludosFiumba1.mp3');
const zringa = new Audio('./audios/saludosZringa.mp3');
const zrumba = new Audio('./audios/saludosZrumba.mp3');
const corona = new Audio('./audios/rdmCorona.mp3');
const farmaceutico = new Audio('./audios/rdmFarmaceutico.mp3');
const forunculo = new Audio('./audios/rdmForunculo.mp3');
const magnum = new Audio('./audios/rdmMagnumefisto.mp3');
const serendipia = new Audio('./audios/rdmSerendipia.mp3');
const llollapalooza = new Audio('./audios/rdmLlollapalooza.mp3');
const perez = new Audio('./audios/namePerez.mp3');
const aguBofe = new Audio('./audios/nameAgustinBofe.mp3');
const nati = new Audio('./audios/nameNatiPeluso.mp3');
const mercedes2 = new Audio('./audios/nameMercedesSosa2.mp3');
const messi = new Audio('./audios/nameLioMessi.mp3');
const jr = new Audio('./audios/nameJR.mp3');
const anuel = new Audio('./audios/nameAnuel.mp3');
const fedeBal = new Audio('./audios/nameFedeBal.mp3');
const robleis = new Audio('./audios/nameRobleis.mp3');
const becerro = new Audio('./audios/nameMariaBecerra.mp3');
const cavernicola = new Audio('./audios/rdmCavernicola.mp3');
const salsa = new Audio('./audios/rdmSalsaDeSoja.mp3');
const venezolano = new Audio('./audios/rdmVenezolano.mp3');
const africano = new Audio('./audios/rdmAfricano.mp3');
const boliviano = new Audio('./audios/rdmBoliviano.mp3');
const instagram = new Audio('./audios/rdmInstagram.mp3');
const corte = new Audio('./audios/corte.mp3');
const buenasNoches = new Audio('./audios/saludosBuenasNoches.mp3');
const morgan = new Audio('./audios/nameMorganFreeman.mp3');
const silvina = new Audio('./audios/nameSilvinaEscudero.mp3');
const silvia = new Audio('./audios/nameSilvia.mp3');
const quincianiera = new Audio('./audios/rdmQuincianiera.mp3');

let sonidos = document.querySelectorAll('button');
console.log(sonidos);
let myArray = Array.from(sonidos);
console.log(myArray);

